[tool.poetry]
name = "pyrecest"
description = "Framework for recursive Bayesian estimation in Python."
readme = "README.md"
authors = ["Florian Pfaff <pfaff@kit.edu>"]
version = "0.4.2"
 
[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = "*"
scipy = "^1.11.0"
matplotlib = "*"
mpmath = "*"
filterpy = "*"
pyshtools = "*"
beartype = "*"
numpy-quaternion = "*"

[tool.poetry.extras]
healpy_support = ["healpy"]

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.2"
pytest = "*"
parameterized = "*"

