[tool.poetry]
name = "pyrecest"
description = "Framework for recursive Bayesian estimation in Python."
readme = "README.md"
authors = ["Florian Pfaff <pfaff@kit.edu>"]
version = "0.2.2"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "*"
scipy = "*"
matplotlib = "*"
mpmath = "*"
filterpy = "*"
pyshtools = "*"
beartype = "*"

[tool.poetry.extras]
healpy_support = ["healpy"]

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.2"
pytest = "*"
parameterized = "*"

