[tool.poetry]
name = "pyrecest"
description = "Framework for recursive Bayesian estimation in Python."
readme = "README.md"
authors = ["Florian Pfaff <pfaff@kit.edu>"]
version = "0.8.0pre"
 
[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = "*"
scipy = "^1.13.0"
matplotlib = "*"
mpmath = "*"
filterpy = "*"
pyshtools = "*"
beartype = "*"
numpy-quaternion = "*"
shapely = "*"
geomstats = "*"

[tool.poetry.extras]
healpy_support = ["healpy"]
pytorch_support = ["torch"]
jax_support = ["jax", "jaxlib", "autograd"]

[tool.poetry.group.dev.dependencies]
healpy = "*"
torch = "*"
jax = "*"
jaxlib = "*"
autograd = "*"
autopep8 = "^2.1.0"
pytest = "*"
parameterized = "*"

[tool.mypy]
check_untyped_defs = true

[tool.ruff]
line-length = 180