[tool.poetry]
name = "pyrecest"
description = "Framework for recursive Bayesian estimation in Python."
readme = "README.md"
authors = ["Florian Pfaff <pfaff@kit.edu>"]
version = "0.6.2totest"
 
[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = "*"
scipy = "^1.11.4"
matplotlib = "*"
mpmath = "*"
filterpy = "*"
pyshtools = "*"
beartype = "*"
numpy-quaternion = "*"
shapely = "*"

[tool.poetry.extras]
healpy_support = ["healpy"]
pytorch_support = ["torch"]

[tool.poetry.group.dev.dependencies]
healpy = "*"
torch = "*"
autopep8 = "^2.0.2"
pytest = "*"
parameterized = "*"

[tool.mypy]
check_untyped_defs = true

[tool.ruff]
line-length = 180