---
name: Build and publish

permissions:
  contents: write

on:
  workflow_run:
    workflows: ["Update version tag"]
    types:
      - completed

jobs:
  update_version_and_build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install --upgrade poetry

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0)
          echo "VERSION=${TAG_NAME}" >> "$GITHUB_ENV"

      - name: Extract repository name
        run: echo "REPO_NAME=$(echo "${GITHUB_REPOSITORY#*/}" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

      - name: Build package
        run: python -m poetry build

      - name: Create GitHub Release and Upload Artifacts
        env:
          VERSION: ${{ env.VERSION }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          artifacts: ./dist/${{ env.REPO_NAME }}-${{ env.VERSION }}-py3-none-any.whl,./dist/${{ env.REPO_NAME }}-${{ env.VERSION }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
